export const WEEK_DAYS = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];
interface ScheduleConstInt {
  [key: string]: object[];
}

export const SCHEDULE: ScheduleConstInt = {
  Monday: [
    { name: "Akshay", type: "message" },
    { name: "Bency", type: "message" },
    { name: "Chaitra", type: "message" },
    { name: "Madhu", type: "call" },
    { name: "Prem", type: "call" },
    { name: "Seema", type: "call" },
    { name: "Vishnupriya", type: "call" },
    { name: "Pallavi", type: "call" },
    { name: "Deepika", type: "call" },
  ],
  Tuesday: [
    { name: "Akshata", type: "call" },
    { name: "Harshita", type: "call" },
    { name: "Latha", type: "call" },
    { name: "Nivedita", type: "message" },
    { name: "Priyanka", type: "message" },
    { name: "Sumita", type: "call" },
    { name: "Manasa", type: "call" },
    { name: "Preeti", type: "call" },
  ],
  Wednesday: [
    { name: "Anantha laskshmi", type: "message" },
    { name: "Bharath", type: "message" },
    { name: "Jithendra", type: "call" },
    { name: "Jyoti", type: "call" },
    { name: "Malati", type: "call" },
    { name: "Narasimha", type: "message" },
    { name: "Rekha", type: "call" },
    { name: "Uday", type: "call" },
    { name: "Darshan", type: "call" },
  ],
  Thursday: [
    { name: "Ahuti", type: "call" },
    { name: "Astha", type: "message" },
    { name: "Chandni", type: "call" },
    { name: "Kavita", type: "message" },
    { name: "Shruti", type: "message" },
    { name: "Venkatesh", type: "call" },
    { name: "Vikram", type: "call" },
    { name: "Shivanshu", type: "call" },
    { name: "Sundar", type: "call" },
  ],
  Friday: [
    { name: "Akhila", type: "call" },
    { name: "Bhanu", type: "message" },
    { name: "Jaya", type: "call" },
    { name: "Jaydutt", type: "call" },
    { name: "Manisha", type: "call" },
    { name: "Sushma", type: "call" },
    { name: "Kavya", type: "call" },
  ],
  Sunday: [
    { name: "Swati", type: "call", isDownLine: true, customClass: "text-gray-500" },
    { name: "Sunaina", type: "call", isDownLine: true, customClass: "text-gray-500" },
    { name: "Drishya", type: "call", isDownLine: true, customClass: "text-gray-500" },
  ],
};

export const USERS = [
  { name: "Kavya", type: "call" },
  { name: "Deepika", type: "call" },
  { name: "Sundar", type: "call" },
  { name: "Darshan", type: "call" },
  { name: "Pallavi", type: "call" },
  { name: "Preeti", type: "call" },
  { name: "Manasa", type: "call" },
  { name: "Uday", type: "call" },
  { name: "Shivanshu", type: "call" },
  { name: "Harshita", type: "call" },
  { name: "Latha", type: "call" },
  { name: "Venkatesh", type: "call" },
  { name: "Akshata", type: "call" },
  { name: "Narasimha", type: "message" },
  { name: "Anantha laskshmi", type: "message" },
  { name: "Manisha", type: "call" },
  { name: "Priyanka", type: "message" },
  { name: "Vishnupriya", type: "call" },
  { name: "Kavita", type: "message" },
  { name: "Astha", type: "message" },
  { name: "Bharath", type: "message" },
  { name: "Prem", type: "call" },
  { name: "Chandni", type: "call" },
  { name: "Akhila", type: "call" },
  { name: "Vikram", type: "call" },
  { name: "Ahuti", type: "call" },
  { name: "Madhu", type: "call" },
  { name: "Chaitra", type: "message" },
  { name: "Bency", type: "message" },
  { name: "Jithendra", type: "call" },
  { name: "Nivedita", type: "message" },
  { name: "Bhanu", type: "message" },
  { name: "Sushma", type: "call" },
  { name: "Seema", type: "call" },
  { name: "Jyoti", type: "call" },
  { name: "Jaya", type: "call" },
  { name: "Akshay", type: "message" },
  { name: "Sumita", type: "call" },
  { name: "Jaydutt", type: "call" },
  { name: "Rekha", type: "call" },
  { name: "Malati", type: "call" },
  { name: "Shruti", type: "message" },
  { name: "Swati", type: "call", isDownLine: true },
  { name: "Sunaina", type: "call", isDownLine: true },
  { name: "Drishya", type: "call", isDownLine: true },
];
